final List<Map<String, dynamic>> dummyUsers = [
  {
    "uid": "user_001",
    "name": "John Doe",
    "email": "johndoe@example.com",
    "profilePic": "https://randomuser.me/api/portraits/men/1.jpg",
    "age": 29,
    "location": "New York, USA",
    "isActive": true,
  },
  {
    "uid": "user_002",
    "name": "Jane Smith",
    "email": "janesmith@example.com",
    "profilePic": "https://randomuser.me/api/portraits/women/2.jpg",
    "age": 25,
    "location": "Los Angeles, USA",
    "isActive": false,
  },
  {
    "uid": "user_003",
    "name": "Michael Brown",
    "email": "michaelbrown@example.com",
    "profilePic": "https://randomuser.me/api/portraits/men/3.jpg",
    "age": 32,
    "location": "Chicago, USA",
    "isActive": true,
  },
  {
    "uid": "user_004",
    "name": "Emily Davis",
    "email": "emilydavis@example.com",
    "profilePic": "https://randomuser.me/api/portraits/women/4.jpg",
    "age": 27,
    "location": "Toronto, Canada",
    "isActive": true,
  },
  {
    "uid": "user_005",
    "name": "Chris Wilson",
    "email": "chriswilson@example.com",
    "profilePic": "https://randomuser.me/api/portraits/men/5.jpg",
    "age": 30,
    "location": "London, UK",
    "isActive": false,
  },
  {
    "uid": "user_006",
    "name": "Sophia Martinez",
    "email": "sophiamartinez@example.com",
    "profilePic": "https://randomuser.me/api/portraits/women/6.jpg",
    "age": 26,
    "location": "Berlin, Germany",
    "isActive": true,
  },
  {
    "uid": "user_007",
    "name": "David Lee",
    "email": "davidlee@example.com",
    "profilePic": "https://randomuser.me/api/portraits/men/7.jpg",
    "age": 28,
    "location": "Seoul, South Korea",
    "isActive": true,
  },
  {
    "uid": "user_008",
    "name": "Olivia White",
    "email": "oliviawhite@example.com",
    "profilePic": "https://randomuser.me/api/portraits/women/8.jpg",
    "age": 31,
    "location": "Paris, France",
    "isActive": false,
  },
  {
    "uid": "user_009",
    "name": "James Anderson",
    "email": "jamesanderson@example.com",
    "profilePic": "https://randomuser.me/api/portraits/men/9.jpg",
    "age": 33,
    "location": "Sydney, Australia",
    "isActive": true,
  },
  {
    "uid": "user_010",
    "name": "Emma Johnson",
    "email": "emmajohnson@example.com",
    "profilePic": "https://randomuser.me/api/portraits/women/10.jpg",
    "age": 24,
    "location": "Tokyo, Japan",
    "isActive": true,
  },
];