// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Rvl5ZVdho7tzupFy5OmewVnbQ40iIqw',
    appId: '1:289616400325:web:5c61ec3a0562d18e4105ac',
    messagingSenderId: '289616400325',
    projectId: 'cmd-f-2025-3ebbb',
    authDomain: 'cmd-f-2025-3ebbb.firebaseapp.com',
    storageBucket: 'cmd-f-2025-3ebbb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHslXLrM13eOZN55pOrAcXYyX210de-jA',
    appId: '1:289616400325:android:2d4c55dc00343fd54105ac',
    messagingSenderId: '289616400325',
    projectId: 'cmd-f-2025-3ebbb',
    storageBucket: 'cmd-f-2025-3ebbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW17kxubbqHUggCnbB8WSKSJs1I6WpzW4',
    appId: '1:289616400325:ios:2c3e1918ab8323424105ac',
    messagingSenderId: '289616400325',
    projectId: 'cmd-f-2025-3ebbb',
    storageBucket: 'cmd-f-2025-3ebbb.firebasestorage.app',
    iosClientId: '289616400325-k2peb8l4q76l15dnbiqen3c2ucbm29o9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pineapple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW17kxubbqHUggCnbB8WSKSJs1I6WpzW4',
    appId: '1:289616400325:ios:2c3e1918ab8323424105ac',
    messagingSenderId: '289616400325',
    projectId: 'cmd-f-2025-3ebbb',
    storageBucket: 'cmd-f-2025-3ebbb.firebasestorage.app',
    iosClientId: '289616400325-k2peb8l4q76l15dnbiqen3c2ucbm29o9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pineapple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Rvl5ZVdho7tzupFy5OmewVnbQ40iIqw',
    appId: '1:289616400325:web:c5b787e08d3db2c84105ac',
    messagingSenderId: '289616400325',
    projectId: 'cmd-f-2025-3ebbb',
    authDomain: 'cmd-f-2025-3ebbb.firebaseapp.com',
    storageBucket: 'cmd-f-2025-3ebbb.firebasestorage.app',
  );
}
